import Footer from "@/components/Layouts/Footer";
import Navbar from "@/components/Layouts/Navbar";
import Topbar from "@/components/Layouts/Topbar";
import Head from "next/head";

const Main = ({ title = "Crypto Guru Deals", children, className }) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Topbar />
            <Navbar />
            <main className={className}>{children}</main>
            <Footer />
        </>
    );
};

export default Main;
